### PR TITLE
Log4cxx

### PR DESCRIPTION
**Pull request by ross-desmond**
Looking to create a release with log4cxx nupack.

We've included the skeleton in choco-packages and have testing compilation with ros2 logging infrastructure when compiling with DEBUG in Windows.

The packages you will want to add for the next release are here:
https://github.com/ross-desmond/choco-packages/releases/tag/2018-12-21-1
(ignore the tag location, that was used before a final merge).

Connected to https://github.com/ros2/rcl_logging/pull/3

### CODE REVIEW

**Comment by nburek** [comment]
It'd be great if we could get this and the related log4cxx change merged in for the next ROS2 Crystal patch (ros2/ros2#647). What are the next steps for this PR? Do you need our help with anything?

**Comment by nuclearsandwich** [comment]
> What are the next steps for this PR?

Thanks for the re-ping. I was genuinely not prepared to receive contributions on this repository as the packages here, while in use, are little more than prototypes.

> Do you need our help with anything?

While looking through the build instructions with this package a couple of things stand out.

1. Did you look at packaging APR and apr-utils independently? That's my general preference but I haven't checked whether it adds additional technical challenges beyond needing to package more software. But if we're going to do this I'd like to do it as right as we can the first time.

2. I see that some sed scripts are being used to patch log4cxx. Is there a reason not to use patch files with the patch utility?

3. I'd love to get builds running with MSBuild like the tinyxml* packages do but that's pretty low on my list of priorities.

**Comment by mjcarroll** [comment]
@nburek friendly ping

**Comment by ross-desmond** [comment]
1. Did you look at packaging APR and apr-utils independently? That's my general preference but I haven't checked whether it adds additional technical challenges beyond needing to package more software. But if we're going to do this I'd like to do it as right as we can the first time.
We did look at packaging these two separately, but log4cxx is compiled into a static library, apr and apr-utils are static libraries and is only needed to compile 
2. I see that some sed scripts are being used to patch log4cxx. Is there a reason not to use patch files with the patch utility?
We followed the recommended build procedure for log4cxx https://logging.apache.org/log4cxx/latest_stable/building/vstudio.html, which include sed scripts. 
3. I'd love to get builds running with MSBuild like the tinyxml* packages do but that's pretty low on my list of priorities.
That would be fantastic, and make building significantly less manual. We had issues with specific apr, apr-utils, and apr-log4cxx not building properly together and it took a while to get to this point.

**Comment by nuclearsandwich** [comment]
Thanks for the context @ross-desmond with that information I think it makes sense to skip packaging the package build-only dependencies for now and get this package built so we can use it while settling on a long term packaging solution for ROS 2 on Windows.

I'll try and get the instructions working with msbuild and we'll get this merged and new packages released.

Once they're released the next step will be to update the Open Robotics build hosts and the installation instructions.

**Comment by nuclearsandwich** [comment]
I set up a Windows host to try these instructions. I was able to build in Debug configuration but ran into issues building for Release. Also I had to run to get the bus before I could grab any screenshots so this is just a note to say that this is moving forward.

I haven't yet tried to get anything going with msbuild since I don't yet know how to account for the solution changes made using gui config tools. My plan is to vcs the project dir and try to pinpoint config file changes between the before and after states.

**Comment by nuclearsandwich** [comment]
Here's a screenshot of the error I encountered building for release. 

@ross-desmond is that something you saw and mitigated? I've torn down the environment and set it up twice and hit this error both times.

release-error

**Comment by emersonknapp** [comment]
@nuclearsandwich I just went through the process myself and the "Additional dependencies on rpcrt4.lib" step is apparently configuration-specific. There's a dropdown at the top of the properties dialog - and if you switch over you can add that additional lib dependency for Release as well.

**Comment by nuclearsandwich** [comment]
>  There's a dropdown at the top of the properties dialog - and if you switch over you can add that additional lib dependency for Release as well.

I thought I'd checked that but perhaps not. I'll give it another shot.

**Comment by nuclearsandwich** [comment]
> > 
> 
> I thought I'd checked that but perhaps not. I'll give it another shot.

Scrapped the workspace and tried again. Something wasn't happy but this time it went through. I've built a package but I can't get a test package to pick it up like I do with the others.

I suppose I should try turning it off and on again.

**Comment by nuclearsandwich** [comment]
After rebooting (it didn't take that long I've just been context switching all day) I am able to find the log4cxx package via CMake and build a minimal broken example.

**Comment by nuclearsandwich** [comment]
:fireworks: The [latest release](https://github.com/ros2/choco-packages/releases/tag/2019-02-15-1) contains this package :fireworks: It hasn't yet been incorporated into the installation instructions as I figured we would wait until we're ready to merge the PR enabling rcl_logging_log4cxx.

**Comment by rutvih** [comment]
Thanks Steven! Is there anything pending/blocking on rcl_logging_log4cxx PR to get these both in to next patch?

**Comment by mjcarroll** [comment]
@rutvih @nuclearsandwich is away for a few days, so I'll help get the PR across the line.  I've kicked off a CI build over here to see where we stand: https://github.com/ros2/rcl_logging/pull/3#issuecomment-465188973

**Comment by rutvih** [comment]
@mjcarroll Thank you!

**Pull request merged**
