### PR TITLE
Bullet from vcpkg and update to 3.17

### PR DESCRIPTION
**Pull request by sloretz**
This updates the instructions for building the bullet choco package to use `vcpkg`, and updates the version to 3.17 since that's what vcpkg offers. I've made sure this new package works by building `--packages-above-and-dependencies tf2_bullet` and testing `--packages-select tf2_bullet test_tf2` on a local windows VM.

The `BulletConfig.cmake` is deleted in favor of using the CMake files provided by the vcpkg install, which I think should solve my problem here: https://github.com/ros2/geometry2/pull/495#discussion_r780616721

### CODE REVIEW

**Comment by sloretz** [comment]
I haven't uploaded the package yet because I'm not sure if these instructions are to be followed before or after this PR is merged: https://github.com/ros2/choco-packages#uploading-packages

**Comment by sloretz** [comment]
[bullet.3.17.zip](https://github.com/ros2/choco-packages/files/8189144/bullet.3.17.zip)

Attached to this comment the built choco package (in a zip archive so github will allow uploading it)

**Comment by nuclearsandwich** [comment]
Is bullet 3 going to be used by all active ROS 2 distros on Windows or will we need to conditionally update the install directions? If we still need bullet 2 for Foxy and Galactic then it will make sense to re-upload it along with the bullet 3 package.

**Comment by nuclearsandwich** [comment]
> I haven't uploaded the package yet because I'm not sure if these instructions are to be followed before or after this PR is merged: [ros2/choco-packages#uploading-packages](https://github.com/ros2/choco-packages#uploading-packages)

I think it makes sense to upload after changes are approved and merged. Thanks for checking!

**Review by nuclearsandwich — APPROVED** [review]
I have a question about co-existence with the bullet 2 package which doesn't block merging this PR.

**Comment by sloretz** [comment]
> Is bullet 3 going to be used by all active ROS 2 distros on Windows or will we need to conditionally update the install directions? If we still need bullet 2 for Foxy and Galactic then it will make sense to re-upload it along with the bullet 3 package.

I don't think we need to uploaded the bullet 2.x package with this one because bullet is a bit odd. As far as I can tell [bullet 3 contains bullet 2](https://github.com/bulletphysics/bullet3/issues/1401#issuecomment-338865069), so this package contains both. I don't think anything in ROS uses the bullet 3 stuff yet.

**Comment by nuclearsandwich** [comment]
> I don't think we need to uploaded the bullet 2.x package with this one because bullet is a bit odd. As far as I can tell [bullet 3 contains bullet 2](https://github.com/bulletphysics/bullet3/issues/1401#issuecomment-338865069), so this package contains both. I don't think anything in ROS uses the bullet 3 stuff yet.

[huh](https://i.giphy.com/media/Ow59c0pwTPruU/giphy.webp). Okay then.

**Pull request merged**
